### ISSUE TITLE
Invalid f-strings

### ISSUE THREAD

**Issue by gaslen** [nikitadurasov/masksembles#2]
Hello and thank you for your interesting work !

Small issue though

**Comment by nikitadurasov** [comment]
Hey @gaslen, thanks a lot for your feedback!

Could you please share your error message? Because if it's `SyntaxError: invalid syntax` pointing to f-string then possibly new python syntax could be an issue. 

`s"{var=}"` syntax is a new feature of python 3.8 [[link]](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging), but now I think it's a good idea to remove it in order to support lower versions of python.

**Comment by gaslen** [comment]
Sorry, I went too fast ! My python version is indeed outdated (3.7)
